# Generated by Django 5.2.17 on 2026-08-21 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_building',
            field=models.ForeignKey(blank=True, help_text="Registered building this vendor is collected from. Must be in the vendor's zone.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='locations.building'),
        ),
    ]
