# Generated by Django 5.2.17 on 2026-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendorprofile_pickup_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text="Dish photo shown in the customer app's listing cards.", null=True, upload_to='menu-items/'),
        ),
    ]
