# Generated by Django 5.2.17 on 2026-08-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Runner cannot go online or claim jobs until admin approves.')),
                ('is_online', models.BooleanField(default=False, help_text='Toggled by the runner in-app. Only online, approved runners see the ready-order job list.')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, help_text='Accumulated delivery-fee earnings pending payout. Written to by the payments app only.', max_digits=10)),
                ('rating_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Cached average rating (e.g. 4.80). Null until the runner has at least one rating.', max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runner_profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runners', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Runner Profile',
                'verbose_name_plural': 'Runner Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
