# Generated by Django 5.2.17 on 2026-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Registration'), ('password_reset', 'Password Reset')], default='register', max_length=20),
        ),
    ]
