# Generated by Django 5.2.17 on 2026-08-20 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Kilimani', 'Nakuru Town'", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive zones are hidden from search/signup but keep their historical data.')),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Flat delivery fee for this zone. Leave blank to use the platform default.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, help_text="Default vendor commission %% for this zone. A VendorProfile's own commission_pct, if set, overrides this.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['name'],
            },
        ),
    ]
