# Generated by Django 5.2.17 on 2026-08-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Green Court Apartments'", max_length=150)),
                ('landmark', models.CharField(blank=True, help_text="e.g. 'Opposite the green kiosk, blue gate'", max_length=255)),
                ('entry_details', models.CharField(blank=True, help_text='e.g. gate/security details for gated compounds', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate rather than delete if a building is mis-registered or no longer valid.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='zones.zone')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, help_text="e.g. 'House 12', 'Flat 3B'", max_length=50)),
                ('label', models.CharField(default='Home', help_text="Customer-facing label, e.g. 'Home', 'Work'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_locations', to='locations.building')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='unique_building_name_per_zone'),
        ),
    ]
